---
- hosts: sasgridmeta1
  become: yes
  become_user: sasinst

  tasks:
  - name: start sas services
    shell: |
      rm /sas/config/Lev1/Web/gemfire/instances/ins_41415/locator41415state.dat 2> /dev/null
      . /usr/local/config/Lev1/sas.servers start

- hosts: sasgridnodes
  become: yes
  become_user: root

  tasks:
  - name: mount saswork
    shell: |
      mdadm -C /dev/md0 --level=raid0 --raid-devices=4 /dev/nvme[0-3]n1
      mkfs.xfs /dev/md0
      mount /dev/md0 /saswork
      chmod 777 /saswork

- hosts: sasgridnodes
  become: yes
  become_user: sasinst

  tasks:
  - name: start sas services
    shell: |
      . /sas/config/Lev1/sas.servers start
      /sas/studioconfig/sasstudio.sh start

